# Site settings
title: Lewatoto
email: 
description: > # this means to ignore newlines until "baseurl:"
  Blog personal en donde publicaré información de mis experimentos, futuros proyectos y alguno que otro tutorial. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Lewatoto.github.io" # the base hostname & protocol for your site
twitter_username: Lewatoto
github_username:  Lewatoto

# Build settings
markdown: kramdown
